# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(null=True)),
                ('probe_no', models.CharField(max_length=200)),
                ('alarm_data', models.CharField(max_length=200)),
                ('alarm_pics', models.CharField(max_length=500)),
                ('spot_name', models.CharField(max_length=100)),
            ],
        ),
    ]
